package org.cardanofoundation.cip113.service;

import com.bloxbean.cardano.client.util.HexUtil;
import org.cardanofoundation.cip113.core.CoreBlueprint;
import org.cardanofoundation.cip113.offline.BootstrapFixture;
import org.cardanofoundation.cip113.offline.OfflineChain;
import org.cardanofoundation.cip113.core.CoreScriptFactory;
import org.cardanofoundation.cip113.model.bootstrap.ProtocolBootstrapParams;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Safety net for parameter application (no chain, no network): re-derives every protocol
 * script hash from a deployment record and asserts each equals the hash that record carries.
 *
 * <p>Agreement is evidence that the parameter shape and order
 * {@link ProtocolScriptBuilderService} applies matches {@code plutus.json}'s
 * {@code validators[].parameters}. It is the check that catches the failure mode
 * {@code AikenScriptUtil.applyParamToScript} makes so easy: it validates neither arity nor
 * type, so a wrong parameter list still yields a perfectly good script under a different
 * hash, and nothing complains until a registry lookup finds no match.
 *
 * <h2>Why this no longer reads the committed devnet JSON</h2>
 *
 * It used to derive against {@code protocol-bootstraps-devnet.json}, the recorded handoff of a
 * real devnet deployment. Every entry in that file predates the validator split: those
 * deployments name a {@code programmable_logic_global} that no longer exists and a
 * {@code programmable_logic_base} whose hash has moved, so the backend now refuses to load
 * them at all. Pointing this test at one would assert that today's parameterisation reproduces
 * a protocol we can no longer build against — which would fail for the right reason, but tells
 * nobody anything useful.
 *
 * <p>So the ground truth is now a deployment built by {@link BootstrapFixture} against the
 * blueprint on the classpath. That is a weaker claim in one way — the record is generated by
 * the same codebase rather than being an independent artefact — and a stronger one in another:
 * the fixture's transaction is actually EVALUATED by the real Plutus scripts in the offline
 * suite, so its parameterisation is not merely self-consistent, it is one the contracts accept.
 * When a fresh devnet deployment exists (see {@code docs/DEVNET-GUIDE.md}), pointing this back
 * at a committed record restores the independence.
 */
class ProtocolScriptBuilderServiceHashDerivationTest {

    private ProtocolScriptBuilderService protocolScriptBuilderService;

    private ProtocolBootstrapParams params;

    @BeforeEach
    void setUp() throws Exception {
        protocolScriptBuilderService = new ProtocolScriptBuilderService(
                new CoreScriptFactory(new CoreBlueprint()));
        params = BootstrapFixture.bootstrap(new OfflineChain()).params();
    }

    @Test
    void programmableLogicBaseHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedProgrammableLogicBaseScript(params);

        assertEquals(params.programmableLogicBaseParams().scriptHash(), script.getPolicyId());
    }

    @Test
    void transferDelegateHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedTransferScript(params);

        assertEquals(params.transferParams().scriptHash(), script.getPolicyId());
    }

    /**
     * The delegate that did not exist before the split. Asserted separately from
     * {@code transfer} rather than assumed to follow from it: the two take the same parameter,
     * so a factory that returned the wrong one of them would still produce a valid script, and
     * the only thing distinguishing them is which blueprint title was resolved.
     */
    @Test
    void thirdPartyDelegateHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedThirdPartyScript(params);

        assertEquals(params.thirdPartyParams().scriptHash(), script.getPolicyId());
    }

    @Test
    void unfrackingDelegateHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedUnfrackingScript(params);

        assertEquals(params.unfrackingParams().scriptHash(), script.getPolicyId());
    }

    @Test
    void registryMintHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedDirectoryMintScript(params);

        assertEquals(params.directoryMintParams().scriptHash(), script.getPolicyId());
    }

    @Test
    void registrySpendHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedDirectorySpendScript(params);

        assertEquals(params.directorySpendParams().scriptHash(), script.getPolicyId());
    }

    @Test
    void issuanceCborHexMintHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedIssuanceCborHexMintScript(params);

        assertEquals(params.issuanceParams().scriptHash(), script.getPolicyId());
    }

    @Test
    void protocolParamsMintHashMatchesDeploymentRecord() throws Exception {
        var script = protocolScriptBuilderService.getParameterizedProtocolParamsMintScript(params);

        assertEquals(params.protocolParams().scriptHash(), script.getPolicyId());
    }

    /**
     * issuance_mint is deliberately NOT asserted against a recorded hash the way the others are.
     * Its 3rd parameter, {@code minting_logic_cred}, is the <em>substandard's</em> issuer script
     * — not part of the protocol bootstrap, and different per token — so there is no fixed
     * "protocol" policy id for issuance_mint in the deployment record to compare against. What
     * the record holds is a split prefix/postfix CBOR template built around a dummy placeholder
     * credential.
     *
     * <p>{@code AikenScriptUtil.applyParamToScript} performs no arity check and no type check, so
     * asserting the output is <em>some</em> well-formed 28-byte hash would pass equally with
     * three parameters applied as with four. So this follows the deployment's own technique:
     * serialise the applied script body, split it on the substandard script's hash (the 3rd
     * parameter, unambiguous and known here), and assert the 4th parameter's bytes landed in the
     * postfix — i.e. after the third.
     *
     * <p>The 4th parameter is now {@code params_policy}, a bare {@code PolicyId}, where it used
     * to be {@code plg_stake_cred}, a {@code Credential}. That is the change this assertion is
     * most worth having for: same position, same arity, and the only observable difference in
     * the output is which bytes appear and whether they are wrapped. A builder left on the old
     * shape would produce a template that looks entirely healthy and derives a policy id
     * {@code registry_mint} refuses for every registration made against it.
     */
    @Test
    void issuanceMintAppliesFourParametersInOrder() throws Exception {
        var substandardIssueScript = protocolScriptBuilderService.getParameterizedAlwaysFailScript("deadbeef");

        var script = protocolScriptBuilderService.getParameterizedIssuanceMintScript(params, substandardIssueScript);

        var serializedBody = HexUtil.encodeHexString(script.serializeScriptBody());
        var substandardHashHex = HexUtil.encodeHexString(substandardIssueScript.getScriptHash());
        var parts = serializedBody.split(substandardHashHex);

        assertEquals(2, parts.length,
                "substandard credential must appear exactly once in the applied issuance_mint body");
        assertTrue(parts[1].contains(params.protocolParams().scriptHash()),
                "params_policy (the protocol-params NFT policy) must be applied after "
                        + "minting_logic_cred — its bytes should appear in the postfix following "
                        + "the substandard credential");
        assertTrue(!parts[1].contains(params.transferParams().scriptHash()),
                "the 4th parameter must be the params policy, NOT the transfer delegate's "
                        + "credential — that is the pre-split shape, and applying it still yields a "
                        + "valid script under a policy id no registration can match");
    }
}
