"use client";

/**
 * The same deployment, offered again in the SDK's record shape.
 *
 * One deployment, two repositories, two files — and they are the same twenty
 * keys in the same order, so this derives the SDK's from ours rather than
 * building a second record that could drift from the first.
 *
 * ## Why the name is asked for rather than guessed
 *
 * The SDK's convention is `deployments/<network>/<instance>.json`, and its
 * harness deliberately has NO default instance: a default is what made "which
 * instance?" an invisible question with a silent answer. Asking keeps the
 * question visible at the only moment the operator knows the answer.
 *
 * ## Why the overwrite warning is here and not a guard
 *
 * `saveInstance` refuses to overwrite, because a record's bootstrap seed UTxOs
 * are one-shot and already spent — a replaced record cannot be regenerated by
 * re-running anything. A browser download cannot overwrite a repository file, so
 * this page CANNOT enforce that rule; the risk lives entirely in how the file is
 * committed afterwards. A warning where the file is produced is the only thing
 * this side can contribute.
 */

import { useState } from "react";
import {
  isSdkInstanceName,
  sdkInstancePath,
  toSdkInstanceRecord,
  serialiseSdkInstance,
  SDK_INSTANCE_NETWORKS,
} from "@/lib/deployment/sdk-record";

export function SdkRecordDownload({
  entry,
  network,
}: {
  /** ONE bootstrap record entry — the caller picks the instance. */
  entry: Record<string, unknown>;
  network: string;
}) {
  const [name, setName] = useState("");
  const [error, setError] = useState<string | null>(null);

  const trimmed = name.trim();
  const nameOk = trimmed.length > 0 && isSdkInstanceName(trimmed);
  // A statement about the SDK's convention, not a gate: Giovanni has ruled out
  // network guards in product tooling, so this labels and still offers.
  const conventional = (SDK_INSTANCE_NETWORKS as readonly string[]).includes(network);

  const download = () => {
    setError(null);
    try {
      const bytes = serialiseSdkInstance(toSdkInstanceRecord(entry));
      const blob = new Blob([bytes], { type: "application/json" });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `${trimmed}.json`;
      a.click();
      URL.revokeObjectURL(a.href);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  return (
    <div className="mt-3 space-y-2 rounded border border-dark-700 bg-dark-950 p-3">
      <p className="text-xs font-semibold text-dark-200">Also record this in the SDK</p>
      <p className="text-[11px] text-dark-400">
        The same deployment in the shape <code>cip113-sdk-ts</code> keeps: our record without the
        array wrapper and without <code>schemaVersion</code>. Byte-equal to what the SDK&apos;s own
        harness writes.
      </p>
      <label className="flex flex-wrap items-center gap-2 text-xs text-dark-200">
        <span>instance name</span>
        <input
          className="w-56 rounded border border-dark-700 bg-dark-900 px-2 py-1 font-mono text-xs text-white focus:border-primary-500/50 focus:outline-none"
          placeholder="alpha5"
          value={name}
          onChange={(e) => setName(e.target.value)}
          spellCheck={false}
        />
      </label>
      {trimmed.length > 0 && !nameOk && (
        <p className="text-[11px] text-red-300">
          Letters, digits, dot, dash or underscore, starting with a letter or digit — the name
          becomes a filename.
        </p>
      )}
      {nameOk && (
        <p className="text-[11px] font-mono text-dark-400">{sdkInstancePath(network, trimmed)}</p>
      )}
      {!conventional && (
        <p className="text-[11px] text-accent-300">
          The SDK&apos;s instance convention covers {SDK_INSTANCE_NETWORKS.join(" and ")}, not{" "}
          {network}. The file is still produced and is still correct — it simply sits outside that
          convention, so nothing in the SDK expects to find it there.
        </p>
      )}
      <button
        type="button"
        onClick={download}
        disabled={!nameOk}
        className="rounded border border-dark-600 bg-dark-800 px-3 py-1.5 text-xs text-dark-100 transition-colors hover:border-primary-500/40 hover:text-primary-400 disabled:cursor-not-allowed disabled:opacity-40"
      >
        Download SDK instance record
      </button>
      <p className="text-[11px] text-accent-300">
        Do not replace an existing record for a live instance. Its bootstrap seed UTxOs are
        one-shot and already spent, so a record that is overwritten cannot be regenerated by
        re-running the deployment — give a new deployment a new name instead. The SDK&apos;s own
        writer refuses to overwrite for this reason; a download cannot, so the care has to happen
        when you commit it.
      </p>
      {error && <p className="text-[11px] text-red-300">{error}</p>}
    </div>
  );
}
