package org.cardanofoundation.cip113.offline;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.cardanofoundation.cip113.core.CoreBlueprint;
import org.cardanofoundation.cip113.core.CoreScriptFactory;
import org.cardanofoundation.cip113.model.bootstrap.ProtocolBootstrapParams;
import org.cardanofoundation.cip113.service.ProtocolScriptBuilderService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Every COMMITTED deployment record must be reproducible from the blueprint on the classpath.
 *
 * <h2>Why this exists even though a derivation test already did</h2>
 *
 * {@code ProtocolScriptBuilderServiceHashDerivationTest} asserts the same property against a
 * {@code BootstrapFixture} — a record this codebase GENERATES. Its own javadoc names the weakness
 * ("the record is generated by the same codebase rather than being an independent artefact") and
 * asks for a committed record to be used once one exists. They exist, and this is that test.
 *
 * <h2>⛔ The bug it was written for, measured on preprod 2026-10-01</h2>
 *
 * The dispatcher ({@code programmable_logic_global}) is parameterised by
 * {@code (transfer, thirdParty, unfrackingParameter)}. The factory passed
 * {@code unfracking.scriptHash} for that third argument instead. On preprod, where unfracking is
 * DISABLED and {@code unfrackingParameter} is the 28-byte zero sentinel, the two differ:
 *
 * <pre>
 *   dispatcher(transfer, thirdParty, unfracking.scriptHash) = a36376d3…   what we built
 *   dispatcher(transfer, thirdParty, unfrackingParameter)   = 24ef08d8…   the record, and the
 *                                                                        credential the bootstrap
 *                                                                        actually REGISTERED
 * </pre>
 *
 * A transfer withdraws-0 from the dispatcher, so it targeted an unregistered reward account and the
 * ledger answered <strong>3141</strong> — "rewards withdrawals must consume rewards in full", a
 * message about balances. Issuing was unaffected because the mint withdrawal set is
 * {@code (issuer_admin, issuanceLogic)} and contains no dispatcher.
 *
 * <p>⚑ AND THE GENERATED FIXTURE COULD NEVER HAVE CAUGHT IT. A fixture bootstraps with unfracking
 * ENABLED, so there {@code unfrackingParameter} EQUALS {@code unfracking.scriptHash} and both
 * spellings agree. Only a record with unfracking disabled distinguishes them — which is precisely
 * what a committed artefact gives and a self-generated one cannot.
 */
class CommittedDeploymentHashesTest {

    private static final Path RESOURCES = Path.of("src/main/resources");

    private record Record(String network, ProtocolBootstrapParams params) {}

    private static List<Record> committedRecords() throws Exception {
        var mapper = new ObjectMapper();
        var out = new ArrayList<Record>();
        try (var files = Files.list(RESOURCES)) {
            for (Path p : files.filter(f -> f.getFileName().toString().startsWith("protocol-bootstraps-"))
                    .filter(f -> f.getFileName().toString().endsWith(".json"))
                    .sorted()
                    .toList()) {
                var network = p.getFileName().toString()
                        .replace("protocol-bootstraps-", "").replace(".json", "");
                var json = Files.readString(p);
                if (json.isBlank() || json.trim().equals("[]")) continue;   // no deployment recorded
                for (var params : mapper.readValue(json, ProtocolBootstrapParams[].class)) {
                    out.add(new Record(network, params));
                }
            }
        }
        return out;
    }

    @Test
    @DisplayName("every committed record's core script hashes re-derive from the blueprint")
    void committedRecordsReDerive() throws Exception {
        var records = committedRecords();

        // ⛔ NON-VACUITY. If no record is found this test passes while asserting nothing — and the
        // whole point is that it reads INDEPENDENT artefacts, so their absence is the failure.
        assertFalse(records.isEmpty(),
                "no committed protocol-bootstraps-*.json record could be read from " + RESOURCES
                        + " — this test is now blind");

        var builder = new ProtocolScriptBuilderService(new CoreScriptFactory(new CoreBlueprint()));
        var problems = new ArrayList<String>();

        for (var r : records) {
            var p = r.params();
            check(problems, r.network(), p.txHash(), "programmableLogicBase",
                    p.programmableLogicBase().scriptHash(),
                    builder.getParameterizedProgrammableLogicBaseScript(p).getPolicyId());
            check(problems, r.network(), p.txHash(), "transfer",
                    p.transfer().scriptHash(),
                    builder.getParameterizedTransferScript(p).getPolicyId());
            check(problems, r.network(), p.txHash(), "thirdParty",
                    p.thirdParty().scriptHash(),
                    builder.getParameterizedThirdPartyScript(p).getPolicyId());
            check(problems, r.network(), p.txHash(), "unfracking",
                    p.unfracking().scriptHash(),
                    builder.getParameterizedUnfrackingScript(p).getPolicyId());
            // THE ONE THAT WAS WRONG. Parameterised by unfrackingParameter, not unfracking's hash.
            check(problems, r.network(), p.txHash(), "programmableLogicGlobal (dispatcher)",
                    p.programmableLogicGlobal().scriptHash(),
                    builder.getParameterizedProgrammableLogicGlobalScript(p).getPolicyId());
            check(problems, r.network(), p.txHash(), "issuanceLogic",
                    p.issuanceLogic().scriptHash(),
                    builder.getParameterizedIssuanceLogicScript(p).getPolicyId());
        }

        if (!problems.isEmpty()) {
            fail("A committed deployment record does not re-derive from the blueprint on the "
                    + "classpath. Every one of these hashes is a credential the bootstrap REGISTERED "
                    + "on chain, so a transaction built from the derived value withdraws-0 from an "
                    + "account nothing registered — ledger code 3141, whose message describes a "
                    + "rewards-balance problem.\n\n" + String.join("\n", problems));
        }
    }

    private static void check(List<String> problems, String network, String txHash,
                              String field, String recorded, String derived) {
        if (recorded == null) return;   // not recorded: nothing to compare
        if (!recorded.equalsIgnoreCase(derived)) {
            problems.add("  " + network + " / " + txHash.substring(0, 16) + "… / " + field
                    + "\n      record  : " + recorded
                    + "\n      derived : " + derived);
        }
    }

    @Test
    @DisplayName("at least one committed record has unfracking DISABLED, or the dispatcher check is blind")
    void aRecordDistinguishesTheTwoSpellings() throws Exception {
        var records = committedRecords();
        assertFalse(records.isEmpty(), "no committed records to inspect");

        // ⛔ THE GUARD ON THE GUARD. When unfracking is ENABLED, unfrackingParameter equals
        // unfracking.scriptHash and passing either produces the same dispatcher — so the test above
        // cannot tell a correct implementation from the bug it exists for. At least one record must
        // carry the sentinel for that assertion to mean anything. If this ever fails, the dispatcher
        // check has gone blind even though it is still green.
        var distinguishing = records.stream()
                .filter(r -> {
                    var d = r.params().programmableLogicGlobal();
                    if (d == null || d.unfrackingParameter() == null) return false;
                    var uf = r.params().unfracking();
                    return uf != null && uf.scriptHash() != null
                            && !d.unfrackingParameter().equalsIgnoreCase(uf.scriptHash());
                })
                .map(Record::network)
                .toList();

        assertFalse(distinguishing.isEmpty(),
                "every committed record has unfrackingParameter == unfracking.scriptHash, so the "
                        + "dispatcher assertion cannot distinguish the two spellings and would pass "
                        + "with the preprod 3141 bug reintroduced. Keep a record with unfracking "
                        + "disabled, or assert the parameterisation another way.");
    }
}
