package org.cardanofoundation.cip113.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.cardanofoundation.cip113.config.AppConfig;
import org.cardanofoundation.cip113.model.blueprint.Plutus;
import org.cardanofoundation.cip113.model.blueprint.Validator;
import org.cardanofoundation.cip113.model.bootstrap.ProtocolBootstrapParams;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

@Service
@RequiredArgsConstructor
@Slf4j
public class ProtocolBootstrapService {

    private final ObjectMapper objectMapper;

    private final AppConfig.Network network;

    @Value("${programmable.token.default.txHash:}")
    private String defaultTxHash;

    /**
     * Start even when no deployment has been recorded yet. DEFAULT FALSE.
     *
     * ⛔ FOR THE WINDOW BEFORE A BOOTSTRAP, AND NOTHING ELSE. Refusing to start is the right
     * behaviour for a service whose entire job is indexing a protocol instance: a backend that
     * boots without one can only answer questions about a protocol that does not exist.
     *
     * But it makes the period BEFORE a deployment unnecessarily blind. The database, the
     * migrations, the node peer and the indexer are all configured independently of any
     * protocol, and with this off there is no way to find out whether they work until after a
     * ceremony has spent one-shot seeds that cannot be recovered. Discovering a misconfigured
     * relay at that point is expensive in a way that discovering it beforehand is not.
     *
     * ⚠ THE SERVICE STILL REFUSES TO ANSWER. This flag moves the failure from startup to the
     * accessor — see {@link #getProtocolBootstrapParams()} — so nothing serves a wrong answer;
     * the process merely stays up long enough to prove the rest of the stack is sound.
     */
    @Value("${cip113.allow-no-deployment:false}")
    private boolean allowNoDeployment;

    @Getter
    private Plutus plutus;

    private ProtocolBootstrapParams protocolBootstrapParams;

    /**
     * The deployment this build serves.
     *
     * ⛔ THROWS rather than returning null, and that is the whole reason this is written out
     * instead of generated by Lombok. Thirteen call sites reach this and none of them checks —
     * correctly, because before {@code allow-no-deployment} existed it could not be null. A
     * null here would surface as a NullPointerException several frames away from the cause,
     * naming a field on a record instead of naming the missing deployment.
     */
    public ProtocolBootstrapParams getProtocolBootstrapParams() {
        if (protocolBootstrapParams == null) {
            throw new IllegalStateException(
                    "No CIP-113 deployment is recorded for this network, so this operation cannot be "
                    + "served. The service started because cip113.allow-no-deployment=true, which is "
                    + "for checking the database, migrations and node peer BEFORE a bootstrap — it does "
                    + "not make protocol operations possible. Deploy from /ops/bootstrap-protocol "
                    + "(which does not need this service), record the result, and restart.");
        }
        return protocolBootstrapParams;
    }

    // Map of txHash -> ProtocolBootstrapParams for all available versions
    private final Map<String, ProtocolBootstrapParams> bootstrapsByTxHash = new ConcurrentHashMap<>();

    @PostConstruct
    public void init() {
        log.info("defaultTxHash: {}", defaultTxHash);
        log.info("network: {}", network.getNetwork());

        try {

            var protocolBootstrapFilename = String.format("protocol-bootstraps-%s.json", network.getNetwork());
            log.info("protocolBootstrapFilename: {}", protocolBootstrapFilename);

            // ⚑ LOADED BEFORE THE DEPLOYMENT CHECK so the refusal below can quote the protocol
            // version this build actually carries, rather than a literal. That literal went stale
            // twice in three releases — alpha.4 -> alpha.5 -> 0.0.1 — and each time it sent
            // somebody looking at their configuration for a mismatch that did not exist.
            plutus = objectMapper.readValue(
                    this.getClass().getClassLoader().getResourceAsStream("plutus.json"),
                    Plutus.class
            );

            // Load array of protocol bootstrap configurations
            var bootstrapsList = objectMapper.readValue(
                    this.getClass().getClassLoader().getResourceAsStream(protocolBootstrapFilename),
                    new TypeReference<List<ProtocolBootstrapParams>>() {}
            );

            // Latest-only: every committed record must describe the exact contract surface
            // this build targets. Keeping unusable entries here turns configuration drift into
            // an ordering-dependent runtime choice, so stale records fail startup immediately.
            bootstrapsByTxHash.clear();
            ProtocolBootstrapParams firstUsable = null;
            for (ProtocolBootstrapParams params : bootstrapsList) {
                requireCurrentSchema(params);
                if (bootstrapsByTxHash.putIfAbsent(params.txHash(), params) != null) {
                    throw new IllegalStateException(
                            protocolBootstrapFilename + " contains duplicate txHash " + params.txHash());
                }
                if (firstUsable == null) firstUsable = params;
                log.info("Loaded protocol bootstrap for txHash: {}", params.txHash());
            }
            if (firstUsable == null) {
                var message = protocolBootstrapFilename + " records no CIP-113 "
                        + plutus.preamble().version() + " deployment for this network.\n"
                        + "\n"
                        + "  THIS IS NOT A DEADLOCK. The bootstrap page does NOT need this service: it\n"
                        + "  builds every transaction from the blueprint bundled with the frontend and\n"
                        + "  talks only to the chain. Deploy from /ops/bootstrap-protocol with this\n"
                        + "  service DOWN, put the record it gives you into " + protocolBootstrapFilename + ",\n"
                        + "  set the indexer's sync-start block, and then start this service.\n"
                        + "\n"
                        + "  To bring this service up BEFORE deploying — to check the database, the\n"
                        + "  migrations and the node peer — set cip113.allow-no-deployment=true. It will\n"
                        + "  start and refuse protocol operations individually instead of failing here.";
                if (!allowNoDeployment) {
                    throw new IllegalStateException(message);
                }
                log.warn("NO DEPLOYMENT RECORDED — starting anyway because "
                        + "cip113.allow-no-deployment=true. Every protocol operation will be refused "
                        + "until a deployment is recorded and this service is restarted.\n{}", message);
            }

            // Set default protocol bootstrap params
            if (defaultTxHash != null && !defaultTxHash.isEmpty()) {
                protocolBootstrapParams = bootstrapsByTxHash.get(defaultTxHash);
                if (protocolBootstrapParams == null) {
                    throw new IllegalStateException(
                            "programmable.token.default.txHash names " + defaultTxHash
                                    + ", which is not a CIP-113 " + plutus.preamble().version() + " deployment in "
                                    + protocolBootstrapFilename);
                }
                log.info("Using default protocol bootstrap with txHash: {}", defaultTxHash);
            } else if (firstUsable != null) {
                protocolBootstrapParams = firstUsable;
                log.info("No default txHash configured, using bootstrap: {}",
                        protocolBootstrapParams.txHash());
            }
            // ⚑ NO else. With allow-no-deployment there is nothing to select, and the branch
            // above dereferenced `firstUsable` unconditionally — which is precisely the hazard
            // this flag introduces: code written when the field COULD NOT be null. Found by
            // StartWithoutDeploymentTest rather than by a container that would not boot.

            log.info("Successfully initialized ProtocolBootstrapService with {} bootstrap versions", bootstrapsByTxHash.size());
        } catch (IOException e) {
            log.error("could not load bootstrap or protocol blueprint", e);
            throw new RuntimeException(e);
        }
    }

    /**
     * Fails fast, at load time, on any deployment record this build cannot actually use.
     *
     * <p>Two distinct problems get the same treatment, because they have the same
     * consequence:
     *
     * <ul>
     *   <li><strong>Wrong schema.</strong> A pre-alpha.4 record cannot describe the merged
     *       protocol-params/registry validators, the replaceable issuance logic, the dispatcher,
     *       or all seven reference-script inputs. Renaming old fields would produce hashes for a
     *       different protocol, so such a deployment has to be redeployed.</li>
     *   <li><strong>Missing components.</strong> Jackson fills absent fields with
     *       {@code null}, and a record handed out with null limbs NPEs the first time a
     *       builder reads one — far from the cause, and only for whichever operation happened
     *       to need that limb.</li>
     * </ul>
     *
     * <p>Both are refused here, naming the record and the reason. The alternative — reading
     * leniently and filling in blanks — yields transactions that are well-formed, submitted,
     * and rejected on chain for reasons that point nowhere near a stale JSON file.
     */
    private static void requireCurrentSchema(ProtocolBootstrapParams params) {
        Integer version = params.schemaVersion();
        if (version == null || version != ProtocolBootstrapParams.CURRENT_SCHEMA_VERSION) {
            throw new IllegalStateException(
                    "Protocol bootstrap entry txHash=" + params.txHash() + " declares schemaVersion="
                            + (version == null ? "none (pre-versioning)" : version)
                            + ", but this build requires " + ProtocolBootstrapParams.CURRENT_SCHEMA_VERSION
                            + ". This development build supports alpha.5 only; deploy and record the current "
                            + "protocol rather than adapting an older record.");
        }

        var missing = new ArrayList<String>();
        if (params.protocolParams() == null || params.protocolParams().policyId() == null
                || params.protocolParams().utxo() == null) missing.add("protocolParams");
        if (params.programmableLogicBase() == null) missing.add("programmableLogicBase");
        if (params.transfer() == null) missing.add("transfer");
        if (params.thirdParty() == null) missing.add("thirdParty");
        if (params.unfracking() == null) missing.add("unfracking");
        if (params.programmableLogicGlobal() == null) missing.add("programmableLogicGlobal");
        if (params.upgradeMultisig() == null || params.upgradeMultisig().txInput() == null
                || params.upgradeMultisig().utxo() == null) missing.add("upgradeMultisig");
        if (params.upgradeAuthority() == null) missing.add("upgradeAuthority");
        if (params.issuanceLogic() == null) missing.add("issuanceLogic");
        if (params.issuance() == null) missing.add("issuance");
        if (params.registry() == null) missing.add("registry");
        if (params.maxInlineDatumBytes() == null) missing.add("maxInlineDatumBytes");
        if (params.programmableBaseRefInput() == null) missing.add("programmableBaseRefInput");
        if (params.programmableLogicGlobalRefInput() == null) missing.add("programmableLogicGlobalRefInput");
        if (params.transferRefInput() == null) missing.add("transferRefInput");
        if (params.thirdPartyRefInput() == null) missing.add("thirdPartyRefInput");
        if (params.unfrackingRefInput() == null) missing.add("unfrackingRefInput");
        if (params.issuanceLogicRefInput() == null) missing.add("issuanceLogicRefInput");
        if (params.upgradeMultisigRefInput() == null) missing.add("upgradeMultisigRefInput");
        if (params.txHash() == null) missing.add("txHash");

        if (!missing.isEmpty()) {
            throw new IllegalStateException(
                    "Protocol bootstrap entry txHash=" + params.txHash()
                            + " declares schemaVersion " + version + " but is missing: "
                            + String.join(", ", missing)
                            + ". Regenerate it from a real deployment rather than hand-editing it.");
        }
    }

    /**
     * Get protocol bootstrap params by transaction hash
     *
     * @param txHash the transaction hash
     * @return the protocol bootstrap params or empty if not found
     */
    public Optional<ProtocolBootstrapParams> getProtocolBootstrapParamsByTxHash(String txHash) {
        return Optional.ofNullable(bootstrapsByTxHash.get(txHash));
    }

    /**
     * Get all available protocol bootstrap configurations
     *
     * @return map of txHash to ProtocolBootstrapParams
     */
    public Map<String, ProtocolBootstrapParams> getAllBootstraps() {
        return Map.copyOf(bootstrapsByTxHash);
    }

    public Optional<String> getProtocolContract(String contractTitle) {
        return plutus.validators().stream()
                .filter(validator -> validator.title().equals(contractTitle))
                .findAny()
                .map(Validator::compiledCode);
    }

}
